Default: &defaults
  user: latitune
  password: latitune
  host: localhost
  port: 5432
  database: latitune
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: latitune_test
  <<: *defaults

Staging:
  database: latitune_staging
  poolsize: 100
  <<: *defaults

Production:
  database: latitune_production
  poolsize: 100
  <<: *defaults
